--CREAR ESQUEMA DE BASE DE DATOS DESARROLLO SISTEMA CLIENTES CUENTAS DEMO
CREATE DATABASE dteccusacc_db;

--CREATE USER 
create user 'uteccusacc'@'%' identified by 'uteccusacc';

--GRANT USAGE ON *.* TO uteccusacc@'%';

GRANT ALL PRIVILEGES ON dteccusacc_db.* to uteccusacc@'%';

FLUSH PRIVILEGES;

USE dteccusacc_db;

--ALTER USER 'uteccusacc'@'%' IDENTIFIED WITH mysql_native_password BY 'uteccusacc';


DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON(
PERSONID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(256) NOT NULL,
LAST_NAME VARCHAR(256) NOT NULL,
GENDER VARCHAR(2),
AGE INT,
IDN VARCHAR(13),
ADDRESS VARCHAR(256) NOT NULL,
PHONE VARCHAR(56) NOT NULL,
EMAIL VARCHAR(256),
CREATEDBY VARCHAR(256) NOT NULL,
CREATEDDATE DATETIME NOT NULL,
MODIFIEDBY VARCHAR(256),
MODIFIEDDATE DATETIME,
STATUS BOOLEAN,
CONSTRAINT ACCPK PRIMARY KEY (PERSONID) 
);

DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER(
CUSTOMERID INT NOT NULL AUTO_INCREMENT,
PASS VARCHAR(256) NOT NULL,
PERSONID INT NOT NULL ,
CREATEDBY VARCHAR(256) NOT NULL,
CREATEDDATE DATETIME NOT NULL,
MODIFIEDBY VARCHAR(256),
MODIFIEDDATE DATETIME,
STATUS BOOLEAN,
CONSTRAINT ACCPK PRIMARY KEY (CUSTOMERID) 
);

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSFKPERPK FOREIGN KEY (PERSONID) REFERENCES PERSON(PERSONID);

DROP TABLE IF EXISTS ACCOUNTTYPE;

CREATE TABLE ACCOUNTTYPE(
ACCTYPID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(256) UNIQUE NOT NULL,
CREATEDBY VARCHAR(256) NOT NULL,
CREATEDDATE DATETIME NOT NULL,
MODIFIEDBY VARCHAR(256),
MODIFIEDDATE DATETIME,
STATUS BOOLEAN,
CONSTRAINT ATPK PRIMARY KEY (ACCTYPID) 
);


DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT(
ACCOUNTID INT NOT NULL AUTO_INCREMENT,
ACCNUMBER INT UNIQUE NOT NULL,
BALANCE DOUBLE NOT NULL,
ACCTYPID INT NOT NULL ,
CUSTOMERID INT NOT NULL ,
CREATEDBY VARCHAR(256) NOT NULL,
CREATEDDATE DATETIME NOT NULL,
MODIFIEDBY VARCHAR(256),
MODIFIEDDATE DATETIME,
STATUS BOOLEAN,
CONSTRAINT ACCPK PRIMARY KEY (ACCOUNTID) 
);

ALTER TABLE ACCOUNT ADD CONSTRAINT ACCFKATPK FOREIGN KEY (ACCTYPID) REFERENCES ACCOUNTTYPE(ACCTYPID);
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCFKCUSPK FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID);

DROP TABLE IF EXISTS TRANSACTIONTYPE;

CREATE TABLE TRANSACTIONTYPE(
TRATYPID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(256) NOT NULL,
DESCRIPTION VARCHAR(256) NOT NULL,
CREATEDBY VARCHAR(256) NOT NULL,
CREATEDDATE DATETIME NOT NULL,
MODIFIEDBY VARCHAR(256),
MODIFIEDDATE DATETIME,
STATUS BOOLEAN,
CONSTRAINT TRATYPPK PRIMARY KEY (TRATYPID) 
);


DROP TABLE IF EXISTS TRANSACTION;

CREATE TABLE TRANSACTION(
TRANSACTIONID INT NOT NULL AUTO_INCREMENT,
AMOUNT DOUBLE NOT NULL,
TRATYPID INT NOT NULL,
CREATEDBY VARCHAR(256) NOT NULL,
CREATEDDATE DATETIME NOT NULL,
MODIFIEDBY VARCHAR(256),
MODIFIEDDATE DATETIME,
STATUS BOOLEAN,
CONSTRAINT TRAPK PRIMARY KEY (TRANSACTIONID) 
);

ALTER TABLE TRANSACTION ADD CONSTRAINT TRAFKTRATYPPK FOREIGN KEY (TRATYPID) REFERENCES TRANSACTIONTYPE(TRATYPID);

DROP TABLE IF EXISTS ACCOUNTTRANSACTION;

CREATE TABLE ACCOUNTTRANSACTION(
ACCTRANID INT NOT NULL AUTO_INCREMENT,
TRANSACTIONID INT NOT NULL,
ACCOUNTID INT NOT NULL,
BALANCEINIT DOUBLE NOT NULL,
BALANCEAVAILABLE DOUBLE NOT NULL,
CREATEDBY VARCHAR(256) NOT NULL,
CREATEDDATE DATETIME NOT NULL,
MODIFIEDBY VARCHAR(256),
MODIFIEDDATE DATETIME,
STATUS BOOLEAN,
CONSTRAINT ACCTRANPK PRIMARY KEY (ACCTRANID) 
);

ALTER TABLE ACCOUNTTRANSACTION ADD CONSTRAINT ATFKACCPK FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID);
ALTER TABLE ACCOUNTTRANSACTION ADD CONSTRAINT ATFKTRAPK FOREIGN KEY (TRANSACTIONID) REFERENCES TRANSACTION(TRANSACTIONID);
